### ISSUE TITLE
How can I log in to the backend page?

### ISSUE THREAD

**Issue by Fzoltan87** [lakasir/lakasir#149] opened 2024-03-24 20:53 UTC
However, the login doesn't work for me.

You can see the login data in the users table.

I open the following link: http://test.localhost:8000/member/login

You enter the data, but nothing happens, I don't even get an error message.

I also created an Admin user in the database and tried to access the interface with him, but nothing happened.

I open the following link: http://localhost:8000/admin/login

**Comment by sheenazien8** [comment] 2024-03-24 23:59
What development package do you use? Are you using herd valet or docker? I think it's because of your local development package, and I'll try it using docker or PHP artisan serve in my local first to reproduce your encounter error

**Comment by sheenazien8** [comment] 2024-03-25 04:37
Solved, sorry for this bug; I found it because I specified the session domain, so I think I don't need a session domain because the app uses multi-tenant

**Comment by Fzoltan87** [comment] 2024-03-25 04:59
Hello. I looked at the project with Xampp, but I think it should be used as well, because the login page loads.

**Comment by sheenazien8** [comment] 2024-03-25 07:57
Ya, I think so. Can you share the bug as a video? And your .env also

**Comment by Fzoltan87** [comment] 2024-03-25 16:14
I just updated the modified code in the morning, now only the main domain is available for me, the subdomain is not (404 error page is displayed)

**Comment by sheenazien8** [comment] 2024-03-25 23:25
Have the database lakasir_test and domain test.localhost been created on yours? Because it's quite strange. and the admin login is running correctly or not?

**Comment by Fzoltan87** [comment] 2024-03-26 05:23
yes, both test.localhost and lakasir_test exist in the data tables. The administrative login works, yes, you can enter the site there.

**Comment by sheenazien8** [comment] 2024-03-26 15:05
> yes, both test.localhost and lakasir_test exist in the data tables. The administrative login works, yes, you can enter the site there.


Okay, I'll try to sort out this strange error; I'll try to use xampp to reproduce what's your issues, I'd be pleased if you could help me sort out this error

**Comment by Fzoltan87** [comment] 2024-03-26 15:25
> > yes, both test.localhost and lakasir_test exist in the data tables. The administrative login works, yes, you can enter the site there.
> 
> Okay, I'll try to sort out this strange error; I'll try to use xampp to reproduce what's your issues, I'd be pleased if you could help me sort out this error

Hi. It must have been a cookie problem, because now it works fine. Now I was able to log in at test.localhost:8000/member/login, so I got to the admin interface. I think this error has been fixed. Thank you for your continued cooperation.

Could a list of urls be included in the description? I'm thinking here about which url address can be used to create a new tenant user, and the use of the API url. Thanks.

**Comment by sheenazien8** [comment] 2024-03-26 15:30
I'm not sure, but I think it's pretty good to have a list of URLs on the description, you can open PR for that, and thanks for your suggestion

**Comment by sheenazien8** [comment] 2024-03-26 15:30
So i'll close this issue if you don't have this issue anymore

**Closed by sheenazien8** 2024-03-26 15:30 UTC

**Comment by Fzoltan87** [comment] 2024-03-26 15:32
> So i'll close this issue if you don't have this issue anymore

Ok, I'll open a new PR for him.
